removed !
jayminard/Modern-Cloud pull request #3
Opened 2024-02-18 21:14 UTC by Newmang314

In this, I removed the ! because it was unneccessary, and because of improvisation because of reviews.

2024-02-18 21:16 UTC, Newmang314 commented
Wait, I forgot to add the al error, my bad.

2024-02-18 21:55 UTC, jayminard requested changes
Please change Al to All in H2 tag

2024-02-18 21:55 UTC, jayminard commented on index.html
I like the changes. Lets fix the spelling in the H2 tag and we should be good.

2024-02-19 15:34 UTC, Newmang314 commented on index.html
Okay.

2024-02-19 17:10 UTC, merged